### ISSUE TITLE
Custom Environment Variables Support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [umijs/umi#1397]
Like [Create React App](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables):
```
.env,
.env.local,
.env.development, .env.test, .env.production,
.env.development.local, .env.test.local, .env.production.local
```

**Comment by sorrycc** [comment]
It's too compilicated, I don't think we really need these.

**Comment by khalibloo** [comment]
@sorrycc could you recommend an alternative perhaps? I need different configurations for dev, staging and production

**Comment by guuibayer** [comment]
@sorrycc, you have a recommendation to use different configurations?

**Comment by khalibloo** [comment]
I found the `define`s work really well in the end. In `.umirc.js`, I can have something like this
```js
export default {
  //...other configs
  //env vars
  define: {
    "APP_ENV": "default",
    "ENDPOINT": "https://www.example.com",
    "THEME": {faveColor: 'blue'}, //objects are supported as well
  },
}
```
And then in the code, you can simply use the variables as like so.
```js
    const baseUrl = ENDPOINT;
    console.log(THEME.faveColor);
```
To use different configs in different environments, you can override them in your other `.umirc.xxx.js` files. For example, I have `.umirc.local.js`, `.umirc.staging.js` and `.umirc.prod.js` where I redefine the variables I want to override. The local one can be kept out of git using gitignore of course.
Finally, on each environment, you use the `UMI_ENV` env variable to determine which config file is used. On my staging env, `UMI_ENV` is set to `staging`, so that `.umirc.staging.js` is used, and so on. Have a look at the docs here https://umijs.org/guide/config.html#configuration-file

**Comment by dimasusername** [comment]
There is a problem with eslint-loader during development
I was able to find this solution: https://github.com/umijs/umi/issues/2160#issuecomment-562769077
