### ISSUE TITLE
after build only spinner is seen

### ISSUE THREAD

**Issue by kambleaa007** [umijs/umi#4054]
## What happens?

after,
npm run build
created folder was,
dist
opened file index.html
it shows only spinner

![image](https://user-images.githubusercontent.com/19818679/75774196-6bd68880-5d75-11ea-92e1-69b3f6cbc283.png)

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue. Use `yarn create umi` then upload to your GitHub

## How To Reproduce

npm run build
open dist
open index.html
sees only spinner nothing else

**Expected behavior** 1. 2.

Must have build whole app rather than only spinner getting on window whole app missing here...

## Context

- **Umi Version**:
- **Node Version**: v 10.15
- **Platform**: windows 10

**Comment by sorrycc** [comment]
Need reproduce step.

**Comment by kambleaa007** [comment]
i should have run my dist folder on html server,
do you know how to deploy mock umi data,
How to do umi serve,
i am deploying on netlify, it took my repo and deployed but login not working it missing mock user credentials

**Comment by sorrycc** [comment]
mock is not for production, maybe you can try umi-mock or umi-serve, https://github.com/umijs/umi/tree/2.x/packages .

**Comment by kambleaa007** [comment]
Hmm, DOcs says `add the umi-server command to the script of package.json`, 
Any example there

**Comment by sorrycc** [comment]
`umi serve`, not `umi server`, umi serve is serve with mock functionality.

**Comment by kambleaa007** [comment]
Yes, i added `"start": "umi-serve"` it works locally, but not after `npm run build` by `Netlify`,  why its not working https://zen-murdock-baaa46.netlify.com/

**Comment by kambleaa007** [comment]
I tried using gh-pages command `npm deploy`, 
changes are `"deploy": "gh-pages -d dist"`

**Comment by IronSean** [comment]
I understand mock data is for development only, but in order to show off front end work without needing to develop backend data I want to be able to deploy to netlify or other locations with mock data enabled. That way UI feedback and suggestions can be gathered and implemented separately while the backend is still being worked on.

Is it possible to export a static version with mock data handing, or does mock data require running a server? Can I deploy static with mock data, or must I host `umi dev` and expose the dev server for this review and testing?
