### ISSUE TITLE
proxy 配置没有效果

### ISSUE THREAD

**Issue by xstxhjh** [umijs/umi#4619]
```javascript
export default defineConfig({
  hash: true,
  antd: {},
  dva: {
    hmr: true,
  },
  // dynamicImport: {
  //   loading: '@/components/PageLoading/index',
  // },
  targets: {
    ie: 11,
  },
  // umi routes: https://umijs.org/docs/routing
  routes: [
    { path: '/', component: '@/pages/index' },
  ],
  // @ts-ignore
  title: false,
  ignoreMomentLocale: true,
  proxy: {
    '/api': {
      target: 'http://rap2.taobao.org:38080/app/mock/253350',
      changeOrigin: true,
      secure: false,
      pathRewrite: { '^/api': '' },
    },
  },
  manifest: {
    basePath: '/',
  },
});
```

```javascript
  request('/api/extraRoutes', {
    method: 'GET',
  }).then((res: any) => {
    // extraRoutes = res.routes
    console.log(res)
  })
```
控制台报错
[HPM] Error occurred while trying to proxy request /extraRoutes from localhost:8001 to http://rap2.taobao.org:38080/app/mock/253350 (ETIMEDOUT) (https://nodejs.org/api/errors.html#errors_common_system_errors)

浏览器接口返回
Error occured while trying to proxy to: localhost:8001/extraRoutes

**Comment by xiaohuoni** [comment]
请检查你的配置，如果对 proxy 有疑问，可以查阅教程 https://www.yuque.com/umijs/umi/proxy

**Comment by caizhehao** [comment]
我也报同样的错误，请问怎么解决的

**Comment by aze759** [comment]
大哥们，解决了吗，项目因为这个上不线，如果解决了能否留言告知一下，**please！**

**Comment by caizhehao** [comment]
已解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: aze759 ***@***.***&gt;
发送时间: 2021年12月7日 16:17
收件人: umijs/umi ***@***.***&gt;
抄送: caizhehao ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [umijs/umi] proxy 配置没有效果 (#4619)





 
大哥们，解决了吗，项目因为这个上不线，如果解决了能否留言告知一下，please！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by caizhehao** [comment]
> 大哥们，解决了吗，项目因为这个上不线，如果解决了能否留言告知一下，**please！**

我这是因为在/etc/hosts文件中没有配置target地址指向才出现了该问题，配置完后就可以了, 127.0.0.1 target-url

**Comment by zhengjialux** [comment]
兄弟   这个问题解决了吗？我也遇到了。。。
