### ISSUE TITLE
spa 模式下 type=hash      history.push({ query: { ts: 122 } }) 第一次导致页面刷新

### ISSUE THREAD

**Issue by chenxu-javascript** [umijs/umi#4852]
## What happens?
umijs 版本从3.1 升级到3.2.3 时候
项目为单页面 即 type = hash
使用 history.push({ query: { ts: 122 } }) 跳转 会导致页面刷新。
而history.push('/?ts=122') 正常

期望页面不刷新

**Comment by regreceive** [comment]
我遇到了同样问题，同时补充一下新情况：

不管是history.push({ query: { ts: 122 } })还是history.push('/?ts=122') ，在首次执行时，都会导致页面根组件重新mount，第二次以后不会。

3.2.6版问题如旧。

**Comment by baohouse** [comment]
Basically this issue is where on initial load of the app, clicking a link that navigates to a different route will cause the page to reload, but subsequent route changes do not reload the page.

I was testing on umi@3.2.10 and this incident was occurring. I revert to umi@3.1.1 and the problem went away. I could not test from 3.1.2 to 3.2.2 because those versions would break my build, so the best I can help with on this issue is that the breaking change occurred somewhere between 3.1.2 and 3.2.3 inclusive.

**Comment by 957739315** [comment]
请问这个问题大家有解决的方法了吗

**Comment by blueway** [comment]
the same

**Comment by codingbycat** [comment]
不知道有什么解决办法，目前已回退到3.1版本了

**Comment by sorrycc** [comment]
最新版不能复现，还有问题的话提供可复现步骤。

**Comment by andy7076** [comment]
同样的问题，最新版本也是这样的。 hash路由push的时候不能配置query参数，加上query的话无法完成跳转操作。
