### ISSUE TITLE
[Feature Request] Support RegExp literals with the `u` flag

### ISSUE THREAD

**Issue by tonywu6** [umijs/umi#8704]
## Background

ES2018 introduces [Unicode Property Escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes). This makes it possible to write regular expressions matching characters with specific Unicode properties, such as scripts and character classes, which is very powerful. For example, the RegExp `[\p{Script=Han}\p{Script=Latin}]` matches all **current and future** Latin characters (ASCII, Latin-1, etc) and Han characters (hanzi, kanji, hanja):

```js
/^[\p{Script=Han}\p{Script=Latin}]+$/gu.test('Appleseed')
// true
/^[\p{Script=Han}\p{Script=Latin}]+$/gu.test('Aufklärung')
// true
/^[\p{Script=Han}\p{Script=Latin}]+$/gu.test('中国智造惠及全球')
// true
/^[\p{Script=Han}\p{Script=Latin}]+$/gu.test('国会議事堂前駅')
// true
```

This has a browser support of 94.77% globally, according to [Can I Use](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes).

To use this feature, the RegExp must be compiled with the new `u` flag. **umi currently does not support using this flag in RegExp literals.** Attempting to introduce this flag results in a compilation error, see [example](https://github.com/tonywu6/umi-4-issue-unicode-regex).

```
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
TypeError: ....tsx: symbol.charCodeAt is not a function
    at symbolToCodePoint (node_modules/@umijs/bundler-utils/compiled/babel/index.js:121445:22)
```

Enabling the `u` flag by invoking the `RegExp` constructor (`new RegExp('...', 'u')`) behaves as expected, however.

## Proposal

Enable this kind of RegExp by default by enabling [`@babel/plugin-proposal-unicode-property-regex`](https://babeljs.io/docs/en/babel-plugin-proposal-unicode-property-regex) (which I think is enabled automatically if the target is ES2018) without requiring users to do it manually using `extraBabelPlugins`.

**Comment by YdreamW** [comment]
This problem is caused by our precompiled `Babel` .  The `rewrite-pattern.js` under the package `regexpu` that plugin `@babel/plugin-proposal-unicode-property-regex` depends on **dynamicly requires** packages under the package `regenerate-unicode-properties`. And these packages depend on the `regenerate` package which has been precompiled in our `Babel`. As a result, the references of  '**required**' `regenerate` and '**precompiled**' `regenerate` are different.

One solution to this problem is to exclude the package `regenerate` when precompiling 'Babel'.  @PeachScript
